// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa-YuMywf78hw2KASUbH6xhv1fhqWb514',
    appId: '1:289588749712:web:dc79adc56cecbe0b6cbf15',
    messagingSenderId: '289588749712',
    projectId: 'news-ade53',
    authDomain: 'news-ade53.firebaseapp.com',
    storageBucket: 'news-ade53.appspot.com',
    measurementId: 'G-3EVET8W98S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6mry0GIp_wu7VWZLucb6LOIw4Gt2eCtM',
    appId: '1:289588749712:android:131cdbca8b5691466cbf15',
    messagingSenderId: '289588749712',
    projectId: 'news-ade53',
    storageBucket: 'news-ade53.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJC_fCb6izRWgbeAGdOlj30d28fuQKxvg',
    appId: '1:289588749712:ios:21c805164e84398a6cbf15',
    messagingSenderId: '289588749712',
    projectId: 'news-ade53',
    storageBucket: 'news-ade53.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJC_fCb6izRWgbeAGdOlj30d28fuQKxvg',
    appId: '1:289588749712:ios:5822e8e76a64d6fb6cbf15',
    messagingSenderId: '289588749712',
    projectId: 'news-ade53',
    storageBucket: 'news-ade53.appspot.com',
    iosBundleId: 'com.example.newsApp.RunnerTests',
  );
}
