// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDysdepFFlp9TiWQyC9gjN9ZHGak-PsOlA',
    appId: '1:153159878206:web:d0820cb6f4ec4fabd3336f',
    messagingSenderId: '153159878206',
    projectId: 'fir-f3a0f',
    authDomain: 'fir-f3a0f.firebaseapp.com',
    databaseURL: 'https://fir-f3a0f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fir-f3a0f.appspot.com',
    measurementId: 'G-GD85DEXKFX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxWlx7iaJUBTDZ8-IbrByU-tXg82acGWQ',
    appId: '1:153159878206:android:a84012d0734053b4d3336f',
    messagingSenderId: '153159878206',
    projectId: 'fir-f3a0f',
    databaseURL: 'https://fir-f3a0f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fir-f3a0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGl-v_D_yWgamF0a3N4plUJTqnl2OkNvI',
    appId: '1:153159878206:ios:38149ef0ecfc6299d3336f',
    messagingSenderId: '153159878206',
    projectId: 'fir-f3a0f',
    databaseURL: 'https://fir-f3a0f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fir-f3a0f.appspot.com',
    iosClientId: '153159878206-fp5la3v4jbsps65m6f4bcc8ihr517fu4.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGl-v_D_yWgamF0a3N4plUJTqnl2OkNvI',
    appId: '1:153159878206:ios:5bc7108a45f80b38d3336f',
    messagingSenderId: '153159878206',
    projectId: 'fir-f3a0f',
    databaseURL: 'https://fir-f3a0f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fir-f3a0f.appspot.com',
    iosClientId: '153159878206-gjkj751jfgfcen276g2422ucgqntcdkj.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsApp.RunnerTests',
  );
}
